# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89323cf58f81952b2886ed0a871b32547e06b7f36182e222cc5e11d3c9bafe0e0ec4e7ec8775ad1091d85e9ecb9aa82a31ccb715ddf98f7bdb32855b429bc604

test:
  secret_key_base: 5ae2d7c0ba734abae0910c0484c54865058dac042fb73af52f85f9784775cbc0fa82e84dc886051f7f482d99cdb8a99a67347c8ca5824131860b9b384df589d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
